
CREATE TABLE TB_DATAAPI_CONFIGURATION(
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `NAME` VARCHAR(50) NOT NULL COMMENT '名称',
  `DESC` VARCHAR(100) DEFAULT NULL COMMENT '描述',
  `CONTENT` TEXT COMMENT '配置内容',
  `ADD_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPD_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE TB_DATAAPI_MAPPER(
  `ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `CONFIGURATION_ID` INT(11) NOT NULL COMMENT '配置ID',
  `URI` VARCHAR(50) NOT NULL COMMENT 'API路径',
  `NAME` VARCHAR(50) NOT NULL COMMENT '名称',
  `DESC` VARCHAR(100) DEFAULT NULL COMMENT '描述',
  `CONTENT` TEXT COMMENT '配置内容',
  `ENABLE` INT(11) NOT NULL DEFAULT 0 comment '是否启用',
  `ADD_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPD_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID),
  UNIQUE KEY `uk_uri` (`URI`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
